### ISSUE TITLE
是否可以增加上传封面参数

### ISSUE THREAD

**Issue by shuizhuyu1015** [leanflutter/flutter_txugcupload#2]
大佬可以增加下高级功能吗，比如上传时附带封面和指定任务流

**Comment by lijy91** [comment]
@shuizhuyu1015 当前是支持传入封面参数的，但是在官方提供的文档未找到指定任务流相关的信息

可查看 `TXPublishParam` 类查看详情的参数支持情况

**Comment by shuizhuyu1015** [comment]
奥，，看到了，大佬回复好快，赞

**Comment by shuizhuyu1015** [comment]
> @shuizhuyu1015 当前是支持传入封面参数的，但是在官方提供的文档未找到指定任务流相关的信息
> 
> 可查看 `TXPublishParam` 类查看详情的参数支持情况

奥，，看到了，大佬回复好快，赞
