### ISSUE TITLE
pod install报错

### ISSUE THREAD

**Issue by shuizhuyu1015** [leanflutter/flutter_txugcupload#3]
pod install 报错，大佬
指向了podfile的26行，是有什么问题

[!] Invalid `Podfile` file: cannot load such file -- /Applications/flutter/packages/flutter_tools/bin/podhelper.

 #  from /Users/mam/Downloads/flutter_txugcupload-master/example/ios/Podfile:26
 #  -------------------------------------------
 #  
 >  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
 #  
 #  -------------------------------------------

**Comment by lijy91** [comment]
这个问题请看这里
https://github.com/flutter/flutter/issues/59522#issuecomment-651271208
