### ISSUE TITLE
导入后iOS运行的时候报错 Could not build module 'flutter_txugcupload' 不知道为什么

### ISSUE THREAD

**Issue by tuchengdong** [leanflutter/flutter_txugcupload#5]

**Comment by lijy91** [comment]
可以提供一个可复现的项目工程吗？

**Comment by lijy91** [comment]
可以参考与下的配置进行修改
https://github.com/leanflutter/flutter_txugcupload#%E9%9B%86%E6%88%90

**Comment by tuchengdong** [comment]
我先按照你的提示修改一下试试看~因为是导入到了自己公司的项目里面了所以 项目工程不太方便提供~

**Comment by tuchengdong** [comment]
我先按照你的提示修改一下试试看因为是导入到了自己公司的项目里面了所以 项目工程不太方便提供.我先修改要是不行的话我就直接写一些原生代码吧

**Comment by tuchengdong** [comment]
其实有按照这个修改,但是没效果,我还是自己写原生的吧 哈哈哈~

**Comment by yichengzou** [comment]
这个问题解决了吗，现在

**Comment by tuchengdong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
